### ISSUE TITLE
Error:- No such module 'SCNPath'

### ISSUE THREAD

**Issue by navjotcheema** [maxxfrazer/ARKit-SCNPath#11]
Im getting No such module 'SCNPath'.

Please suggest. attachéd is the screenshot.

<img width="1399" alt="Screenshot 2020-01-24 at 5 55 19 PM" src="https://user-images.githubusercontent.com/4949505/73069166-04562f00-3ed3-11ea-99a7-07d51d412267.png">

**Comment by maxxfrazer** [comment]
@navjotcheema thanks for the issue!
The error is that SCNPath is not an imported package, you can see the directory on the left where the swift files are just brought in. I've updated the master branch.
