### ISSUE TITLE
Getting distance between you and path.

### ISSUE THREAD

**Issue by alicelovalvo** [maxxfrazer/ARKit-SCNPath#12]
Hi,
This is just an improvement or a question... is there a way to calculate the minimum distance between the path and the center of the camera? Supposing that you are not on the path and you want to calculate the minimum distance between you and the path.
Another option is: instead to calculate the distance, is there a way to check if the focusNode is on the path or not?
Thanks in advance.

**Comment by maxxfrazer** [comment]
To check if focusNode is on the path, all you really need to do is check if a hitTest at the centre of the screen hits the geometry of the SCNPath.

For the minimum distance to any point on the path, or any one of the control points, you can use this package I'd previously made for routing graphs. Build up the graph with `SCNPathNode.path` and then check Graph3D.findPointOnEdge(), or to find the closest control point use Graph3D. findNearestNode(). Passing the camera transform position as the parameter to each function.

**Comment by maxxfrazer** [comment]
FYI finding the closest point on the graph will only consider the centre of the path.

I wouldn't include something like that in this repository as SCNPath has the sole purpose of creating the geometry, not for being an end-to-end graphing and AR wayfinding package.

**Comment by alicelovalvo** [comment]
Thank you very much for your answer!
