### ISSUE TITLE
The Path is created is display against the wall

### ISSUE THREAD

**Issue by navjotcheema** [maxxfrazer/ARKit-SCNPath#14]
Hi I have implemented the Scnpath.
But the problem im facing is that im able to see the path across the wall.
PFA is attached screenshot
![IMG_223C274CC3D0-1](https://user-images.githubusercontent.com/4949505/88841565-bf9dae80-d1fb-11ea-9d9f-4f58783c132c.jpeg)

**Comment by maxxfrazer** [comment]
To hide the path you need to create a mesh in the place of the wall with a hider material, as demonstrated in the example project.

**Comment by navjotcheema** [comment]
Can you please help me where it has done that will be a great help for me.
Thanks

**Comment by navjotcheema** [comment]
I don't know how to create mesh, if you had done that please help !!

**Comment by maxxfrazer** [comment]
It is in the example project, as mentioned:
https://github.com/maxxfrazer/ARKit-SCNPath/blob/main/Example/SCNPath%2BExample/ViewController%2BOcclusions.swift

But this package does not aim to make an end-to-end app, simply to create a path mesh in SceneKit.

**Comment by navjotcheema** [comment]
Hi Max, 
Your example does not seems to working fine I just want the exact way it is displaying in your demo video that path is not visible  on the curve.Iim not expecting end to end App but the way you demo in video it should work like that.
I will be very great full if you can help in  this.
Thanks

**Comment by maxxfrazer** [comment]
Did you check the above file? If there's still and error and you're sure that the configuration is scanning the wall but not creating the mesh by calling the methods found in the mentioned file above; then please open an issue using the template provided (that for some reason was ignored).
I'll take a look into it then once I know a bit more about your environment and what debugging you have already done to figure out the issue.

**Comment by navjotcheema** [comment]
The only issue I'm facing is white wall. If there is white wall the Anchors are not detecting vertical area.So is there anything you can help with white wall issue?

**Comment by maxxfrazer** [comment]
The example depends on ARKit being able to detect a wall via the horizontal and vertical plane detection; there is no extra algorithm I've added to do this.
