### ISSUE TITLE
Occlusions working with iOS 12?

### ISSUE THREAD

**Issue by andrewbradnan** [maxxfrazer/ARKit-SCNPath#2]
I was trying to get occlusions going with 12.1.4 and they no longer seems to work.  Any clue?  (Not that I tried with 11)

**Comment by maxxfrazer** [comment]
@andrewbradnan Make sure that `renderer(renderer:, didAdd node:, for anchor:)` and `renderer(_ renderer:, didUpdate node:, for anchor:)` are being called.
ARKit doesn't detect *all* surfaces, only those with some contrast as in the GIF examples.
The Example is still working great for me and it actually relies on iOS 12+ for the occlusion.

I've switched on notifications for this repo - didn't realize they were off, but please @ me next time so I get a ping 👍

**Comment by maxxfrazer** [comment]
I'm going to go ahead and close this due to lack of response and not being able to repeat.
