### ISSUE TITLE
Can't install the pod file into the project?

### ISSUE THREAD

**Issue by Rjmaurya13** [maxxfrazer/ARKit-SCNPath#5]
Below is the error.
[!] Unable to find a specification for `SCNPath`

**Comment by maxxfrazer** [comment]
Please create an issue with the template provided:
https://github.com/maxxfrazer/ARKit-SCNPath/issues/new?assignees=maxxfrazer&labels=&template=issue-bug-all-in-one.md&title=
And give more information on the issue, otherwise there is nothing I can do to help
