### ISSUE TITLE
Add ability to store map/paths and retrieve

### ISSUE THREAD

**Issue by talkaboutdesign** [maxxfrazer/ARKit-SCNPath#6]
Not really a bug, just a feature request. Would it be possible to add a way to store map data and paths to retrieve later.

**Comment by maxxfrazer** [comment]
@talkaboutdesign not sure what you mean exactly?
This is intended just to turn 3d coordinates into a geometry; if you store the `[SCNVector3]` array then wouldn't that be the only data you need to store?

**Comment by talkaboutdesign** [comment]
Yea sorry for the confusion. I guess I am still trying to wrap my head around this. I'll give you an example. Lets say I'm in a room thats 25 feet by 25 feet and I have a few paths preconfigured in the geometry. I am then trying to render a specific path to get to an item. Where I am struggling is in figuring out how do I know where the user is in relation to the location itself. I was thinking of also saving AR World map. Let me know if I am making any sense here.

**Comment by kanyaneepromma** [comment]
I wonder if your path drifting from original location too? I have problem
like in this video.
https://youtu.be/0CJ_mmwJSAc

ในวันที่ ศ. 16 ส.ค. 2019 เวลา 02:40 Maksim Petriv <notifications@github.com>
เขียนว่า:

**Comment by maxxfrazer** [comment]
@talkaboutdesign @medusawitch I believe you’re both confusing this package with an end-to-end AR navigation solution. This package should be used only as a geometry construction tool for AR and non-AR 3D environments. It’s very minimal for this reason, and any accounting for drift should be taken care of my ARKit or yourself; not by a package which creates a geometry.

Does that make sense?

**Comment by kanyaneepromma** [comment]
I asked if you have experience with arkit problem too.

ในวันที่ ศ. 16 ส.ค. 2019 เวลา 12:40 Max Cobb <notifications@github.com>
เขียนว่า:

**Comment by maxxfrazer** [comment]
Yes I have experienced drift using ARKit (and any SLAM tech really)
I have tried to relocalise the user every 15-20 meters using known markers or other techniques in the past

**Comment by maxxfrazer** [comment]
Could @talkaboutdesign or @medusawitch elaborate a little more on what functionality they're looking for?

As right now it seems like saving an AR World map is neither something a package is required for, or something that's relevant for a package for generating geometries given points. I could be mistaken with what feature you'd like to add.

If you want to open a PR with the feature added yourself then please feel free.

**Comment by maxxfrazer** [comment]
If what you're really looking for @talkaboutdesign is a routing graph, then see this repository:
https://github.com/maxxfrazer/Swift-Graph3D

**Comment by talkaboutdesign** [comment]
@maxxfrazer would love to see some sample code to get an idea of what Graph3D does. Basically the use case I have is this: 

I am in a room and there are objects located at different areas of it. When a user selects on of the items from a list a path shows up in AR to guide them to it. 

Hope this explains it a bit more. If you know of a repo that does something similar to this I would love some input. 

Thanks

**Comment by maxxfrazer** [comment]
Sounds like you're looking for a package to make a full navigation app for you, which unfortunately this is not. To do that there's a lot of work you'll need to do, as I have done previously in other closed source projects.

The repo I linked to is for generating a routing graph, but I haven't gotten around to creating documentation for that, but I have written a test case for it which will show how to do some of it.

The closest open project I'm aware of would be something like [ARCL](https://github.com/ProjectDent/ARKit-CoreLocation).

**Comment by maxxfrazer** [comment]
I think there's not much more I can add here, so I'm going to close this issue.

In the future please try to follow the Issue Template, I put it there to try understand issues like this one a bit faster.
