### ISSUE TITLE
ARSmartHItTest error

### ISSUE THREAD

**Issue by navjotcheema** [maxxfrazer/ARKit-SCNPath#9]
Hello Im getting error in ViewController class

Error:-
Cannot assign value of type 'ARSCNView?' to type 'ARSmartHitTest?'

Line no :- 38
       self.focusSquare.viewDelegate = self.sceneView

Please suggest.

**Comment by maxxfrazer** [comment]
Hi @navjotcheema, thanks for this! I'll take a look into it ASAP

**Comment by maxxfrazer** [comment]
@navjotcheema updated the Example now to work with the latest version of [FocusNode](https://github.com/maxxfrazer/ARKit-FocusNode)

Please confirm the changes work for you!

Thanks.

**Comment by navjotcheema** [comment]
Hi Maxx,
Thanks for the update , after taking fresh download it giving error now:-
x-xcode-log://0BEA4827-A46F-4879-A616-FD51AFA1108B Missing package product 'FocusNode', please fix package resolution errors before building.
Kindly suggest

Thanks

**Comment by maxxfrazer** [comment]
@navjotcheema the example does not import the package, I will need you to tell me what you are opening with Xcode to see this issue. Please try to be as descriptive as the issue template (which you ignored) suggests.

**Comment by maxxfrazer** [comment]
@navjotcheema I will need you to tell me what you are opening with Xcode to see this issue, as I'm not seeing it with `SCNPath+Example.xcodeproj`. Please try to be as descriptive as the issue template (which you did not use) suggests.

**Comment by navjotcheema** [comment]
@maxxfrazer  please find the attached screen shot, hope that help you to rectify the issue.
<img width="1417" alt="ErrorScreenShot" src="https://user-images.githubusercontent.com/4949505/69604598-f192bb80-1043-11ea-90fe-10ae3aa1fc49.png">

**Comment by maxxfrazer** [comment]
@navjotcheema that isn't even this repository, no wonder I couldn't find the issue.

**Comment by navjotcheema** [comment]
In your repository the swift package dependency are missing.
Please review again the screen shots.
<img width="1404" alt="Screenshot 2019-11-26 at 12 45 53 PM" src="https://user-images.githubusercontent.com/4949505/69607227-cf506c00-104a-11ea-8394-79e4e04baffa.png">
<img width="1408" alt="Screenshot 2019-11-26 at 12 46 01 PM" src="https://user-images.githubusercontent.com/4949505/69607228-cf506c00-104a-11ea-8174-65a2fb1ca37b.png">

**Comment by maxxfrazer** [comment]
Okay that's the correct repo. Strange, I just re-cloned and have no issues, the only warning is an "update to swift 5"
<img width="1399" alt="Screen Shot 2019-11-26 at 07 29 02" src="https://user-images.githubusercontent.com/5754073/69608052-7834a200-101e-11ea-9b79-529976d78142.png">

Could you send a screenshot of the swift packages tab? Is it possible that you do not have GitHub SSH set up and that's causing the issue?

**Comment by navjotcheema** [comment]
<img width="868" alt="Screenshot 2019-11-26 at 1 04 32 PM" src="https://user-images.githubusercontent.com/4949505/69608383-569edf00-104d-11ea-9ded-4658168933e3.png">

This one  you asking for?

**Comment by maxxfrazer** [comment]
No, the one for swift packages as in the image I gave

**Comment by maxxfrazer** [comment]
Also RE GitHub SSH

**Comment by navjotcheema** [comment]
Okay Please check:-
<img width="1398" alt="Screenshot 2019-11-26 at 1 06 33 PM" src="https://user-images.githubusercontent.com/4949505/69608508-9c5ba780-104d-11ea-99d9-cdb879e1d45e.png">

**Comment by maxxfrazer** [comment]
Okay I think I know the issues, for one I don't think you're cloning the repository, you're just downloading a zip? if that's the case then either clone the repository instead of downloading a zip, or replace the package with the location:
`git@github.com:maxxfrazer/ARKit-SCNPath.git`

If also you do not have GitHub SSH set up (again, do you?), then you'll need to replace them with the http locations instead:
https://github.com/maxxfrazer/ARKit-SCNPath.git
and
https://github.com/maxxfrazer/ARKit-FocusNode.git

**Comment by navjotcheema** [comment]
Thanks I have added the ssh Key and it worked.
Now the error is no such module Focus Node.
Do i need to install pods as well?

<img width="1398" alt="Screenshot 2019-11-26 at 1 20 17 PM" src="https://user-images.githubusercontent.com/4949505/69609438-8949d700-104f-11ea-811a-e34e6b661fb7.png">

**Comment by maxxfrazer** [comment]
It looks like you have deleted and not re-added the FocusNode dependency

**Comment by bartasx** [comment]
I can confirm that it works now

**Comment by maxxfrazer** [comment]
Hooray! Thanks for confirming @bartasx 

Whenever opening issues please try to be descriptive as possible, and follow the Issue template whenever one is provided, it can often help get to the solution much faster

**Comment by maxxfrazer** [comment]
@navjotcheema I'm assuming you've stopped responding because it's also working for you now.

**Comment by navjotcheema** [comment]
Sorry I got busy..
I havenot deleted anything its not working. :(

**Comment by navjotcheema** [comment]
From where to add focus node dependency

**Comment by maxxfrazer** [comment]
For information on how to use Swift Packages take a look at this
https://developer.apple.com/documentation/xcode/adding_package_dependencies_to_your_app

**Comment by maxxfrazer** [comment]
If you just clone the repository instead of downloading a zip, have GitHub SSH set up, then you will not have issues

**Comment by maxxfrazer** [comment]
I've updated the project to work even for people who aren't using git now, so there should be no further issues of this type. Please do read the linked article though.
